apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: prom-pv
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    path: "/mnt/prometheus/"
    server: "143.215.128.212"
